name: CI/CD

on:
  pull_requests:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Run flake8
        uses: julianwachholz/flake8-action@v2

      - name: Run PEP8 (Linter)
        uses: quentinguidee/pep8-action@v1

      - name: Run mypy
        uses: jpetrucciani/mypy-check@master

  publish:
    name: Publish
    if: |
      (
        github.event_name == 'push'
        || github.event_name == 'workflow_dispatch'
      )
      && (
        github.ref == 'refs/heads/publish'
      )

    runs-on: ubuntu-latest
    needs: 
      - lint

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build and publish
      env:
        TWINE_USERNAME: $TWINE_USERNAME
        TWINE_PASSWORD: $TWINE_PASSWORD
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
